## Introduction: 

This exercise introduces the concept of conditional probability .. In this ex. we will need to import conditional.py .. 

http://greenteapress.com/thinkstats/conditional.py


Imagine that someone you know is pregnant, and it is the beginning of Week 39. What is the chance that the baby will be born in the next week? 
How much does the answer change if it’s a first baby?
We can answer these questions by computing a conditional probability, which is (ahem!) a probability that depends on a condition. In this case, the condition is that we know the baby didn’t arrive during Weeks 0–38. 

Here’s one way to do it:

1. Given a PMF, generate a fake cohort of 1000 pregnancies. For each number of weeks, x, the number of pregnancies with duration x is 1000 PMF(x)

2. Remove from the cohort all pregnancies with length less than 39

3. Compute the PMF of the remaining durations; the result is the conditional PMF

4. Evaluate the conditional PMF at x = 39 weeks

This algorithm is conceptually clear, but not very efficient. A simple alternative is to remove from the distribution the values less than 39 and then renormalize.

## Ex. 2.7: 
- Write a function that implements either of these algorithms and computes the probability that a baby will be born during Week 39, given that it was not born prior to Week 39.

- Generalize the function to compute the probability that a baby will be born during Week x, given that it was not born prior to Week x, for all x. Plot this value as a function of x for first babies and others.



In [1]:
import survey
import first
# import conditional
import Pmf
import numpy as np

In [2]:
## weeks ==> x , read from preg data 
## compute PMF(x)
## preg with x is 1000*pmf(x)

table = survey.Pregnancies()
table.ReadRecords()

# preg = range(1000) ## fake cort of 1000 pregnencies

In [3]:
## extract outcome column .. 

x = np.zeros([len(table.records), 1])

for i in xrange(len(table.records)):
    x[i] = table.records[i].prglength

    
len(x), x

(13593, array([[ 39.],
        [ 39.],
        [ 39.],
        ..., 
        [  5.],
        [ 39.],
        [ 39.]]))

In [4]:
import itertools
merged = list(itertools.chain(*x))
len(merged)

13593

In [5]:
pmf_ = Pmf.MakePmfFromList(merged) 
pmf_.d

{0.0: 0.0011035091591260209,
 1.0: 0.0006621054954756124,
 2.0: 0.005738247627455308,
 3.0: 0.011108658868535275,
 4.0: 0.03030971823732804,
 5.0: 0.013315677186787318,
 6.0: 0.03994703156036195,
 7.0: 0.012874273523136909,
 8.0: 0.030089016405502836,
 9.0: 0.043698962701390426,
 10.0: 0.010078716986684324,
 11.0: 0.014860590009563747,
 12.0: 0.01250643713676157,
 13.0: 0.03281100566468035,
 14.0: 0.0021334510409769737,
 15.0: 0.002869123813727654,
 16.0: 0.0032369602001029946,
 17.0: 0.01861252115059222,
 18.0: 0.0012506437136761569,
 19.0: 0.0025012874273523137,
 20.0: 0.0013242109909512249,
 21.0: 0.002721989259177518,
 22.0: 0.010814389759435003,
 23.0: 0.0008828073273008167,
 24.0: 0.0022805855955271097,
 25.0: 0.0011035091591260209,
 26.0: 0.008607371441182963,
 27.0: 0.0005885382182005444,
 28.0: 0.002795556536452586,
 29.0: 0.0016920473773265653,
 30.0: 0.014566320900463475,
 31.0: 0.0021334510409769737,
 32.0: 0.008975207827558302,
 33.0: 0.0036783638637534026,
 34.0: 0.004414

# Challenge !

In [6]:
len(pmf_.d)  ## only 50 rows !! :S

50

In [7]:
pmf_.d.keys()

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 50.0]

In [8]:
#preg = pmf_.d.values()*1000
#len(preg)
## len = 50000 !! .. it doesn't make sense .. since we need each element to be multiplied by 1000 

p = []
k = []
for i in xrange(len(pmf_.d.values())):
    p.append(pmf_.d.values()[i]*1000)
    k.append(pmf_.d.keys()[i])
    

In [9]:
len(p), k

(50,
 [0.0,
  1.0,
  2.0,
  3.0,
  4.0,
  5.0,
  6.0,
  7.0,
  8.0,
  9.0,
  10.0,
  11.0,
  12.0,
  13.0,
  14.0,
  15.0,
  16.0,
  17.0,
  18.0,
  19.0,
  20.0,
  21.0,
  22.0,
  23.0,
  24.0,
  25.0,
  26.0,
  27.0,
  28.0,
  29.0,
  30.0,
  31.0,
  32.0,
  33.0,
  34.0,
  35.0,
  36.0,
  37.0,
  38.0,
  39.0,
  40.0,
  41.0,
  42.0,
  43.0,
  44.0,
  45.0,
  46.0,
  47.0,
  48.0,
  50.0])

## Concern !! 

del2wty el klam dah mish accurate .. el mafrood enn el keys teb2a el weeks, i.e. 39 .. not 1, 2, 3 ..
This is why we gonna implement our own pmf .. !

Conditional probability for PMF ==> http://sites.stat.psu.edu/~jiali/course/stat416/notes/chap3.pdf

In [10]:
p = []
for i in x:
    p.append(i/len(x))

In [12]:
len(p), p

(13593,
 [array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00279556]),
  array([ 0.00294269]),
  array([ 0.00308983]),
  array([ 0.00286912]),
  array([ 0.00257485]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00272199]),
  array([ 0.00066211]),
  array([ 0.0002207]),
  array([ 0.00242772]),
  array([ 0.00242772]),
  array([ 0.00286912]),
  array([ 0.00036784]),
  array([ 0.00301626]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00058854]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00308983]),
  array([ 0.00272199]),
  array([ 0.00294269]),
  array([ 0.00088281]),
  array([ 0.00301626]),
  array([ 0.00279556]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00286912]),
  array([ 0.00125064]),
  array([ 0.00176561]),
  array([ 0.0004414]),
  array([ 0.00286912]),
  array([ 0.00264842]),
  array([ 

## This is corrrect ;) 
As it makes more sense !

In [18]:
p_1000 = []
for i in p:
    p_1000.append(i*1000)

In [19]:
p_1000

[array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.79555654]),
 array([ 2.94269109]),
 array([ 3.08982565]),
 array([ 2.86912381]),
 array([ 2.5748547]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.72198926]),
 array([ 0.6621055]),
 array([ 0.22070183]),
 array([ 2.42772015]),
 array([ 2.42772015]),
 array([ 2.86912381]),
 array([ 0.36783639]),
 array([ 3.01625837]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 0.58853822]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 3.08982565]),
 array([ 2.72198926]),
 array([ 2.94269109]),
 array([ 0.88280733]),
 array([ 3.01625837]),
 array([ 2.79555654]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 2.86912381]),
 array([ 1.25064371]),
 array([ 1.76561465]),
 array([ 0.44140366]),
 array([ 2.86912381]),
 array([ 2.64842198]),
 array([ 0.9563746]),
 array([ 2.64842198]),
 array([ 2.942

## Challenge:
I don't get it ! :S .. 

why we need to multiply by 1000 !! :S .. 
and why we need to remove all <= 39 after multiplying not before ! :S ..

Let's try the traditional case .. 

In [20]:
greater_than_39 = []
for i in x:
    if(i >= 39):
        greater_than_39.append(i)

In [21]:
## greater_than_39 carries all >= 39 preg
greater_than_39

[array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 40.]),
 array([ 42.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 41.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 42.]),
 array([ 40.]),
 array([ 41.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 40.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 40.]),
 array([ 40.]),
 array([ 41.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 40.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([ 39.]),
 array([

In [ ]:
## I think it makes more sense to consider them in conditional prob calc ! .. 

## Please revisit this part again ! :S