##  Introduction:

This notebook is about Relative risk and we gonna work on pregnency dataset ..

Create a file named risk.py. Write functions named ProbEarly, PropOnTime and ProbLate that take a PMF and compute the fraction of births that fall into each bin. 

Hint: write a generalized function that these functions call.

Make three PMFs, one for first babies, one for others, and one for all live births. For each PMF, compute the probability of being born early, on time, or late.

In [1]:
import Pmf
import numpy as np
import matplotlib.pyplot as plt
import survey
import first
%matplotlib inline 

In [2]:
all_ages = [30, 20, 25, 40, 50, 25]
all_ages

[30, 20, 25, 40, 50, 25]

In [3]:
all_ages_prob = Pmf.MakePmfFromList(all_ages)
all_ages_prob

In [4]:
# ProbEarly (PMF_) ... return age <= 37

def ProbEarly (all_ages_prob):
    
    PMF_ = all_ages_prob.d.values()
    ages = all_ages_prob.d.keys()
    early_v = []
    early_k = []
    
    for j in xrange(len(ages)):
        if(ages[j] <= 37):
            early_v.append(PMF_[j])
            early_k.append(ages[j])
    return early_v, early_k

In [5]:
ProbEarly(all_ages_prob)

([0.3333333333333333, 0.16666666666666666, 0.16666666666666666], [25, 20, 30])

## Comment: 

It makes sense .. 

Let's apply the concept on pregnency data to check its performance .. 

First of all, we have to import survey.py and first.py to be able to extract the first babies, and others data .. and then we can call ProbEarly on them .. 

## But:
first_baby and others represent data (i.e. indices of pmf) but not the pmf values themselves ! .. 
Hence, we have to calc them ourselves !! .. 

How can we calculate pmf ?! .. is it just a value over sum of all values in a list ?! .. let's try to check ! 

In [6]:
x = [3.0,4.0,5.0]
p = []
for i in x:
    p.append(i/12)
p

[0.25, 0.3333333333333333, 0.4166666666666667]

Let's call pmf.makePmfFromList and check if it matches the output of p values .. 


In [7]:
Pmf.MakePmfFromList(x).d

{3.0: 0.3333333333333333, 4.0: 0.3333333333333333, 5.0: 0.3333333333333333}

It doesn't !! :S 

This means that Pmf is just the freq. of each element / count of the list ! 

In [8]:
table = survey.Pregnancies()
table.ReadRecords()

In [9]:
## extract outcome column .. 

outcome_ = np.zeros([len(table.records), 1])

for i in xrange(len(table.records)):
    outcome_[i] = table.records[i].outcome

outcome_

array([[ 1.],
       [ 1.],
       [ 1.],
       ..., 
       [ 2.],
       [ 1.],
       [ 1.]])

In [10]:
alive = 0

for baby in outcome_:
    if (baby == 1):
        alive = alive + 1
    else:
        continue 
alive

9148

In [11]:
all_alive = []

for baby in outcome_:
    if (baby == 1):
        all_alive.append(baby)
    else:
        continue 
all_alive 

[array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1.]),
 array([ 1

ALL values are ones ! .. expected ! .. 

they will represent the data and we gonna compute their pmf to be able to call ProbEarly with them ..

In [12]:
# let's calculate pmf ..

pmf_ = []
for i in all_alive:
    pmf_.append(i/len(all_alive))
pmf_

[array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.00010931]),
 array([ 0.

Same pmf values and it makes sense !

If I called Pmf.makePmfFromList directly, it gave me an error of ==> unhashable type: 'numpy.ndarray' .. 
I think the problem is that all_alive is seen as list of lists .. 
this is why we need to convert it to just (list) ! .. 

Chain() ==> https://docs.python.org/2/library/itertools.html

In [27]:
import itertools
merged = list(itertools.chain(*all_alive))

In [32]:
pmf_ = Pmf.MakePmfFromList(merged) 
ProbEarly(pmf_)

([1.0], [1.0])

I doubt that this result makes sense .. however, let's continue with calc first_babies and others and check at the end

In [14]:
t = first.MakeTables()
original_table = t[0]
firsts_table = t[1]
others_table = t[2]

original_table, firsts_table, others_table

(<survey.Pregnancies at 0x8a22860>,
 <survey.Pregnancies at 0x9bd8588>)

In [15]:
len(original_table), len(firsts_table), len(others_table) ## same results 

(13593, 4413, 4735)

In [16]:
first_ = []
count = 0
for i in alive:
    count = count +  1
#     first_[i] = original_table.records[i].birthord
count

TypeError: 'int' object is not iterable

In [6]:
# PropOnTime (PMF_) ... return age 38 - 40


In [7]:
# ProbLate (PMF_) ... return age >= 41